k8s-helper: &k8s-helper
  docker:
  - image: nginx:$VERSION
  steps:
  - run:
      command: |
          echo $AWS_ACCESS_KEY_ID
          echo $AWS_SECRET_ACCESS_KEY
          ls -ll
          nginx --version

version: 2.1
jobs:
  build:
  << : *k8s-helper
